### ISSUE TITLE
[BUG] MC is ending the world and returns to mainmenu, while chopping a tree

### ISSUE THREAD

**Issue by Cape-City** [PandaDap2006/Pandas-Falling-Trees#21]
Hi,

something isn't as it should be ;)

When Chopping a tree, after the block breaks this happens:

![grafik](https://github.com/PandaDap2006/Pandas-Falling-Trees/assets/122229367/22478b6a-dbbc-4749-80d4-91333c08df8d)

[latest.log](https://github.com/PandaDap2006/Pandas-Falling-Trees/files/12046981/latest.log)

This error wasn't there in version fallingtrees-1.19.3-1.20.1+0.4.3-beta.jar, but in every newer version.

There is also a incompat due your mod and the TreeChop Mod (TreeChop-1.19.3-fabric-0.17.9.jar), but that is not the issue with this crash. I tested it also without TreeChop and MC still ends the world with an error.

**Comment by PandaDap2006** [comment]
i will see if i can figure out why this is happening.

**Comment by natpalmer-e4o4** [comment]
From my non-java developer, non-minecraft modder perspective, it seems like merging the changes from master related to accessing the level object into the 1.19.2 branch may resolve the issue here (see: https://github.com/PandaDap2006/Pandas-Falling-Trees/compare/MC-1.19.2...master#diff-847b7fd7b49518ede08015c5c5dc79b9b3456e7e1b78e0222be4ccb271a5972a)

I would test it myself but I don't have even the slightest clue how to set up a java build environment or what toolchain is involved with mod development.

**Comment by PandaDap2006** [comment]
You would be correct but the code in master is a complete recode of the mod while 1.19.2 is still only the latest released version.

**Comment by natpalmer-e4o4** [comment]
Yeah, I realized the more I looked that the whole codebase was completely refactored and wasn't quite that simple of a fix, which led me to delete my second comment. Regardless, thank you for creating this mod!

**Comment by PandaDap2006** [comment]
This should not be an issue anymore.
