### ISSUE TITLE
[Potential Suggestion] config to only fell tree when player using a woodcutting tool

### ISSUE THREAD

**Issue by MrKashew** [PandaDap2006/Pandas-Falling-Trees#7]
I’ve noticed during gameplay that we can fell trees by hand. This feature is fun but may feel overpowered, as I do see axe durability is subtracted for the entire tree correctly. What are your thoughts on this feature ask, and happy 4th if you’re in America 🎇

**Comment by PandaDap2006** [comment]
Im planning on making it take longer to mine the log with hand based on the amount of logs the tree contains, but adding your suggestion is good too, i think i will add both as configurable features.

Im closing this issue because its not relly an issue, but i will add an suggestion channel to my discord.
